### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@^2.0.0 || ^3.0.0

### ISSUE THREAD

**Issue by logix2** [nemanjan00/uniread#17]
Trying to install the latest Uniread on Linux (Ubuntu 18.04 64bit) fails:
```
$ npm install -g uniread
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
/home/logix/.npm-packages/bin/uniread -> /home/logix/.npm-packages/lib/node_modules/uniread/bin/uniread.js
/home/logix/.npm-packages/lib
└─┬ uniread@0.1.14 
  ├── epub@0.2.1  (git+https://github.com/nemanjan00/epub.git#e1dcd0a7494b4922a3b0a0dc2787ee573b11c2cc)
  └── UNMET PEER DEPENDENCY webpack@^2.0.0 || ^3.0.0

npm WARN pdfjs-dist@2.0.489 requires a peer of webpack@^2.0.0 || ^3.0.0 but none was installed.
npm WARN worker-loader@1.1.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none was installed.
npm WARN schema-utils@0.4.5 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none was installed.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
```
Installation worked a few days ago so I guess it's due to the new PDF dependency/feature.

**Comment by nemanjan00** [comment]
Is it just WARN or error? 

From what I see, it did get installed... 

You should not worry about webpack...

**Comment by nemanjan00** [comment]
I am going to guess you fixed this problem and close the issue. If you did not, I will reopen it.

**Comment by logix2** [comment]
It didn't install initially when I posted the bug report but it does install now. By the way, I didn't receive any email notifications with your replies and only got one today when you closed the bug (I think it's related to GDPR or something).

**Comment by nemanjan00** [comment]
Nice to hear it works for you now. :)
