### ISSUE TITLE
Error while installing using npm

### ISSUE THREAD

**Issue by xorob0** [nemanjan00/uniread#5]
When trying to install using npm I got the error 
`npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive`

**Comment by nemanjan00** [comment]
What is your node/npm version? Which OS?

**Comment by nemanjan00** [comment]
I think it should work now. If not, please, publish the rest of the log. :)

**Comment by xorob0** [comment]
Sorry, my bad, I tried a reboot and it worked. You can close, thanks !
