### ISSUE TITLE
Adding WPM(Words Per Minute) metrics alongside speed

### ISSUE THREAD

**Issue by ketansingrole** [nemanjan00/uniread#55]
I have enjoyed the experience of the application so far but I think adding WPM will be a easy and quick way to find out with which speed the reader is currently as it is the standard. 

the easiest way I can think of is (1000/speed)*60 will give us WPM 1000/ speed because the speed is in miliseconds and 60 because its words per minute.

I am new to opensource and as I think this task is easy enough can I make the contribution for the same feauture I might need a lot of guidence throughout the task. 

@nemanjan00

**Comment by nemanjan00** [comment]
I have just resolved it with this commit

https://github.com/nemanjan00/uniread/commit/0131841866c35fc46ff97ef87949edfb7d9d38cb

**Comment by ketansingrole** [comment]
Thank you
