### ISSUE TITLE
Cannot open any book

### ISSUE THREAD

**Issue by Shirobachi** [nemanjan00/uniread#68]
Hi, 

I installed this package by command `sudo npm install -g uniread` and after that I run `uniread file.pdf` it returned errors like on this screenshot: 
![image](https://user-images.githubusercontent.com/16509749/124308957-512f4200-db6a-11eb-8cde-0b87ba8b7ba0.png)

I am not sure what happened, but according to instruction, I think it should work. 

PS. Furthermore, I use Ubuntu 21.04

Thanks for help in advance!

**Comment by Shirobachi** [comment]
#60

**Comment by nemanjan00** [comment]
Fixed with version 0.0.28
