### ISSUE TITLE
Count comma, point and newline as words (display the last word longer)

### ISSUE THREAD

**Issue by Melkor333** [nemanjan00/uniread#8]
Especially when a sentence ends, it would be very useful to have the last word shown twice the length of a word. This is especially helpful if there are many short sentences.

I myself didn't have much problems with commas, but I guess it would still be good if a comma is like "half a word" timewise...

For newlines, an even longer break the size of like 2 words may be helpful, because rapid context changes can be very confusing.

**Comment by nemanjan00** [comment]
Finished this. :)

Update :)
